name       : gst-python
version    : 1.4.0
release    : 1
source     :
    - http://gstreamer.freedesktop.org/src/gst-python/gst-python-1.4.0.tar.xz : b1e40c29ceb41b03f08d38aca6056054f0341d0706276326dceeec6ac8d53d3e
license    : LGPL-2.1
summary    : GStreamer Python Bindings Supplement
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(pygobject-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
