name       : gst-python
version    : 1.12.4
release    : 9
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.12.4.tar.xz : 20ce6af6615c9a440c1928c31259a78226516d06bf1a65f888c6d109826fa3ea
license    : LGPL-2.1
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(pygobject-3.0) # bug T3904
    - pkgconfig(python3)
setup      : |
    mkdir b2
    mkdir b3
    cd b2
    export PYTHON=/usr/bin/python
    ../configure %CONFOPTS%
    cd ../b3
    export PYTHON=/usr/bin/python3
    ../configure %CONFOPTS%
build      : |
    cd b2
    export PYTHON=/usr/bin/python
    %make
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make
install    : |
    cd b2
    export PYTHON=/usr/bin/python
    %make_install
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make_install
