name       : gst-python
version    : 1.14.4
release    : 14
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.14.4.tar.xz : d0fdb24f93b6d889f309d2f526b8ea9577e0084ff0a62b4623ef1aed52e85a1b
license    : LGPL-2.1-or-later
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(pygobject-3.0) # bug T3904
    - pkgconfig(python3)
setup      : |
    mkdir b2
    mkdir b3
    cd b2
    export PYTHON=/usr/bin/python
    ../configure %CONFOPTS%
    cd ../b3
    export PYTHON=/usr/bin/python3
    ../configure %CONFOPTS%
build      : |
    cd b2
    export PYTHON=/usr/bin/python
    %make
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make
install    : |
    cd b2
    export PYTHON=/usr/bin/python
    %make_install
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make_install
