name       : gst-python
version    : 1.16.1
release    : 17
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.16.1.tar.xz : b469c8955126f41b8ce0bf689b7029f182cd305f422b3a8df35b780bd8347489
license    : LGPL-2.1-or-later
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
environment: |
    export PYTHON=/usr/bin/python3
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
check      : |
    %ninja_check
