name       : gst-python
version    : 1.10.4
release    : 6
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.10.4.tar.xz : 59508174b8bc86c05290aa9a7c5d480ac556a6f36306ddbc1d0eacf4f7868212
license    : LGPL-2.1
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - pkgconfig(pygobject-3.0)
setup      : |
    mkdir b2
    mkdir b3
    cd b2
    export PYTHON=/usr/bin/python
    ../configure %CONFOPTS%
    cd ../b3
    export PYTHON=/usr/bin/python3
    ../configure %CONFOPTS%
build      : |
    cd b2
    export PYTHON=/usr/bin/python
    %make
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make
install    : |
    cd b2
    export PYTHON=/usr/bin/python
    %make_install
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make_install
