name       : gst-python
version    : 1.8.2
release    : 4
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.8.2.tar.xz : 4f5015239482014c16f435559a45e6c87930340b65ee04e2e6fa164c8d724d97
license    : LGPL-2.1
summary    : GStreamer Python Bindings Supplement
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(python-3.5)
    - pkgconfig(pygobject-3.0)
setup      : |
    export PYTHON=/usr/bin/python3
    %configure
build      : |
    %make
install    : |
    %make_install
