name       : gst-python
version    : 1.8.2
release    : 5
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.8.2.tar.xz : 4f5015239482014c16f435559a45e6c87930340b65ee04e2e6fa164c8d724d97
license    : LGPL-2.1
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - pkgconfig(pygobject-3.0)
setup      : |
    mkdir b2
    mkdir b3
    cd b2
    export PYTHON=/usr/bin/python
    ../configure %CONFOPTS%
    cd ../b3
    export PYTHON=/usr/bin/python3
    ../configure %CONFOPTS%
build      : |
    cd b2
    export PYTHON=/usr/bin/python
    %make
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make
install    : |
    cd b2
    export PYTHON=/usr/bin/python
    %make_install
    cd ../b3
    export PYTHON=/usr/bin/python3
    %make_install
