name       : gst-python
version    : 1.18.2
release    : 19
source     :
    - https://gitlab.freedesktop.org/gstreamer/gst-python/-/archive/1.18.2/gst-python-1.18.2.tar.gz : a6e6eff3f298e51022471c2e5d03f64cb69b21a9c2bc2c591c18d8a32083e0b0
license    : LGPL-2.1-or-later
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
rundeps    :
    - gstreamer-1.0-plugins-base
environment: |
    export PYTHON=/usr/bin/python3
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
check      : |
    %ninja_check
