name       : gst-python
version    : 1.16.0
release    : 15
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.16.0.tar.xz : 55dc7aaed1855565f9b9ef842d93e93bfc5cb2b376faef6af5b463e1774e2d38
license    : LGPL-2.1-or-later
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
environment:
    export PYTHON=/usr/bin/python3
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
check      : |
    %ninja_check
